version: '3.8'

services:
  backoffice:
    image: ${DOCKER_REGISTRY-}backoffice
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: .docker/entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/appBackOffice
